# Generated by Django 6.0.6 on 2026-07-15 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('report_type', models.CharField(choices=[('cbc', 'Complete Blood Count'), ('lft', 'Liver Function Test'), ('kft', 'Kidney Function Test'), ('thyroid', 'Thyroid Profile'), ('lipid', 'Lipid Profile'), ('diabetes', 'Diabetes Report'), ('general', 'General')], default='general', max_length=50)),
                ('test_names', models.JSONField(blank=True, default=list)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_reports/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('report_type', models.CharField(blank=True, max_length=100)),
                ('patient_age', models.CharField(blank=True, max_length=50)),
                ('patient_gender', models.CharField(blank=True, max_length=50)),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('safety_note', models.TextField(blank=True)),
                ('overall_risk_level', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
        model_name="medicalreport",
        name="parser_mode",
        field=models.CharField(max_length=50, blank=True),
        ),
        
        migrations.AddField(
        model_name="medicalreport",
        name="error_message",
        field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MedicalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('borderline', 'Borderline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('simple_explanation', models.TextField(blank=True)),
                ('explanation_sources', models.JSONField(blank=True, default=list)),
                ('doctor_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='reports.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('blocked_diagnosis_claims', models.JSONField(blank=True, default=list)),
                ('blocked_treatment_advice', models.JSONField(blank=True, default=list)),
                ('blocked_false_reassurance', models.JSONField(blank=True, default=list)),
                ('safety_warnings', models.JSONField(blank=True, default=list)),
                ('final_safety_status', models.CharField(choices=[('passed', 'Passed'), ('review_required', 'Review Required'), ('blocked', 'Blocked')], default='passed', max_length=30)),
                ('reviewed_text_excerpt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_audits', to='reports.medicalreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
