# Generated by Django 6.0.6 on 2026-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='parser_message',
            field=models.TextField(blank=True),
        ),
    ]
