# Generated by Django 6.0.6 on 2026-08-07 11:20

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_parser_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='file',
            field=models.FileField(upload_to=reports.models.medical_report_upload_path),
        ),
    ]
